apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
  - name: appcontainer
    image: imranvisualpath/freshtomapp:V7
    ports:
      - name: web-svc
        containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-svc
spec:
  selector:
    app: vproapp
  ports:
  - port: 8090
    protocol: TCP
    nodePort: 30001
    targetPort: web-svc
  type: NodePort

---

# vproapp Pod And SVC And LoadBalancer
apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - name: vproapp-port
          containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: svc-elb
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer