AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  S3RoleInstanceProfile:
    Description: Name of the base stack with all infra-resources
    Type: String
    Default: JenkS3Role # SET THE NAME AS THE S3-ROLE EXPORT VALUE
  SGStalkName:
    Description: Security group for the Jenkins Instance
    Type: String
    Default: Jenkins
  KeyName:
    Type: String # GET THE KEYNAME FROM THE MASTER TEMPLATE
  InstanceType:
    Type: String
Mappings: 
  RegionMap: 
    us-east-1: 
      "AMI": "ami-06aa3f7caf3a30282"
    us-east-2: 
      "AMI": "ami-0e731c8a588258d0d"

Resources:
  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      SecurityGroupIds:
        - !ImportValue 
          'Fn::Sub': "${SGStalkName}-SecurityGroupID"
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: "${S3RoleInstanceProfile}-InstanceProfileName"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update
            sudo apt install openjdk-17-jdk maven -y
            sudo apt install wget -y

            # Installing Jenkins
            
            sudo wget -O /usr/share/keyrings/jenkins-keyring.asc  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
            echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
            sudo apt-get update
            sudo apt-get install jenkins -y
            sleep 3
            sudo systemctl start jenkins
      Tags:
        - Key: "Name"
          Value: !Join [" ", ["Jenkins", "in", !Ref AWS::Region]]
