AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cf-s3-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: "/"
      Policies:
        - PolicyName: cf-s3-policies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 'arn:aws:s3:::*'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: cf-s3-ins-profile
      Path: "/"
      Roles:
        - !Ref S3Role
Outputs:
  S3RoleDetails:
    Description: CICD S3 ROLE
    Value: !Ref InstanceProfile
    Export:
      Name: S3Role-S3ProfileName