AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VPCcidr:
    Description: "cidr block for the vpc setup"
    Type: String
    Default: "10.0.0.0/16"
  PublicSubnet1Cidr:
    Description: "cidr block for public subnet 1"
    Type: String
    Default: "10.0.1.0/24"
  PublicSubnet2Cidr:
    Description: "cidr block for public subnet 2"
    Type: String
    Default: "10.0.2.0/24"
  PublicSubnet3Cidr:
    Description: "cidr block for public subnet 3"
    Type: String
    Default: "10.0.3.0/24"

Resources:
  ApplicationVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCcidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: "BANKING_VPC"
  PublicSubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: bank-public-subnet-1
  PublicSubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: bank-public-subnet-2
  PublicSubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ApplicationVPC
      CidrBlock: !Ref PublicSubnet3Cidr
      AvailabilityZone: "us-east-1c"
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: bank-public-subnet-3
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: bank-internet-gateway
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref ApplicationVPC
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ApplicationVPC
      Tags: 
        - Key: Name
          Value: "bank-route-table"
  RouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
  PublicSubnetOneRouuteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetOne
  PublicSubnetTwoRouuteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetTwo
  PublicSubnetThreeRouuteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnetThree

Outputs:
  VpcIdDetails:
    Description: The ID of the VPC Created
    Value: !Ref ApplicationVPC
    Export:
      Name: Vpc-ID
  PublicSubnetOneID:
    Description: The ID of subnet 1
    Value: !Ref PublicSubnetOne
    Export:
      Name: Pub-Subnet-1-ID
  PublicSubnetTwoID:
    Description: The ID of subnet 2
    Value: !Ref PublicSubnetTwo
    Export:
      Name: Pub-Subnet-2-ID
  PublicSubnetThreeID:
    Description: The ID of subnet 3
    Value: !Ref PublicSubnetThree
    Export:
      Name: Pub-Subnet-3-ID