def COLOR_MAP = [
  'SUCCESS': 'good', 
  'FAILURE': 'danger',
]

pipeline{
  agent any
  environment{
    VERSION_LABEL = "V${BUILD_NUMBER}"
  }
  stages{
    stage('Fetch code from GitHub'){
      steps{
        git branch: 'master', url: 'https://github.com/Horpeyemi007/JAVA-WITH-SPRING-BOOT.git'
      }
    }
  }

  post {
    always {
      echo "Slack Notifications."
      slackSend channel: '#jenkins-cicd',
      color: COLOR_MAP[currentBuild.currentResult],
      message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
    }
  }
}