pipeline{
  agent any
  environment{
    AWS_REGION = 'us-east-1'
    APPLICATION_NAME = 'JavaBeanstalkApplication'
    ENVIRONMENT_NAME = 'banking-beanstalk-env'
    S3_BUCKET = 'springboot-artifacts'
    VERSION_LABEL = "V${BUILD_NUMBER}"
  }
  stages{
    stage('Fetch code from GitHub'){
      steps{
        git branch: 'master', url: 'https://github.com/Horpeyemi007/JAVA-WITH-SPRING-BOOT.git'
      }
    }
    stage('Build'){
      steps{sh 'mvn clean package'}
    }
    stage('Updoad to S3'){
      steps{
        sh 'aws s3 cp target/banking-v1.jar s3://${S3_BUCKET}/demoApp-${VERSION_LABEL}.jar'
      }
    }
    stage('Upload to Beanstalk'){
      steps{
        withAWS(region:'us-east-1'){
          sh "aws elasticbeanstalk create-application-version --application-name ${APPLICATION_NAME} --version-label ${VERSION_LABEL} --source-bundle S3Bucket=${S3_BUCKET},S3Key=demoApp-${VERSION_LABEL}.jar"
          sh "aws elasticbeanstalk update-environment --application-name ${APPLICATION_NAME} --environment-name ${ENVIRONMENT_NAME} --version-label ${VERSION_LABEL}"
        }
      }
    }
  }
  post{
    always{
      echo "Finished......"
    }
  }
}