- name: Understanding precedence of Variables
  hosts: all
  become: yes
  vars:
    USRNM: playUser
    COMM: Playbook Variable
    AGE: 22
    NAME: Opeyemi
    SKILLS: DevOps
  tasks:
    - name: Create a user
      user:
        name: "{{NAME}}"
        comment: "{{COMM}}"
      register: usrout

    - debug:
        var: usrout