- name: SetUp a Provisioning Server
  hosts: all
  become: yes
  tasks:
    - name: Inatall NTP on Amazon-EC2
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == 'Amazon'
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip
        - tree

    - name: Install ZIP on Ubuntu
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      loop:
        - wget
        - git
        - unzip
        - zip
        - tree
        - ntp

    - name: Print OS Family Names
      debug:
        var: ansible_os_family

    - name: Start and enable NTP on Amazon-EC2
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'

    - name: Add Groups
      group:
        name: devops
        state: present

    - name: Add Users
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop:
        - user1
        - user2
        - user3
        - user4
        - user5

    - name: Add Another user
      user:
        name: "{{item}}"
        state: present
        groups: devops
      loop: "{{usernames}}"

