- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create Key Pair
      ec2_key:
        name: sample-key
        region: us-east-1
      register: keyout

    #- name: Print AWS Private keyout
    #  debug:
    #    var: keyout

    - name: Save keyout Content
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
      when: keyout.changed

    - name: Launch An EC2 Instance.
      ec2:
        key_name: sample-key
        instance_type: t2.micro
        image: ami-090fa75af13c156b4
        wait: yes
        exact_count: 1
        region: us-east-1
        instance_tags:
          Name: db01
        count_tag:
          Name: db01
      register: output

    - name: Print EC2 Output
      debug:
        var: output

    - name: Delete the role
      iam_role:
        name: Ansible
        assume_role_policy_document: "{{ lookup('file', 'policy.json') }}"
        state: absent