- name: Setup Web Server
  hosts: webgrp
  become: yes
  tasks:
    - name: Install Apache HTTPD
      yum:
        name: httpd
        state: present
    - name: Start and Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

- name: Setup DB Server
  hosts: dbgrp
  become: yes
  vars:
    dbname: groups
    dbuser: devops
    dbpass: admin123
  tasks:
    - debug:
        msg: "Value of dbuser is {{dbuser}}"
    - name: Install maria-DB Server
      yum:
        name: mariadb-server
        state: present
    - name: Install MYSQL Python
      yum:
        name: MySQL-python.x86_64
        state: present
    - name: Start and Enable maria-DB Server
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create a new database with name 'ACCOUNT'
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
      mysql_user:
       name: "{{dbuser}}"
       password: "{{dbpass}}"
       priv: '*.*:ALL,GRANT'
       state: present
       