Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0277155c3f0ab2930
      # Adding tags to the Instance
      Tags:
       - Key: "Name"
         Value: "MyFirstInstance"
       - Key: "Tag2"
         Value: !Join
            - " "
            - - "My instance in"
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref MyInstanceSG

  MyInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  
