Parameters:
  KeyPair:
    Description: DEMO CICD STACK KEY
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  S3RoleStalk:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/demo-cicd-stack/demo-stack-folder/AuthRole.yml
  SecurityGroupStalk:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3RoleStalk
    Properties:
      TemplateURL: https://s3.amazonaws.com/demo-cicd-stack/demo-stack-folder/SG.yml
  JenkinsInstance:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupStalk
    Properties:
      TemplateURL: https://s3.amazonaws.com/demo-cicd-stack/demo-stack-folder/Jenkins.yml
      Parameters:
        KeyName: !Ref KeyPair