- name: Setup vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Setup Variables
      include_vars: vpc_variables.yml

    - name: Import Bastion Variables
      include_vars: output_vars.yml

    - name: Create Vprofile EC2 key
      ec2_key:
        name: sample
        region: "{{region}}"
      register: keyout

    - debug:
        var: keyout

    - name: Store Login Key For bastion Host
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample_key.pem
        mode: 0600
      when: keyout.changed

    - name: Create SG for bastion host
      ec2_group:
        name: BastionSG
        description: Allow 22 from anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 22
        tags:
          Name: BastionSG
      register: BastionSG_out

    - name: Create Bastion EC2 Instance
      ec2:
        key_name: "{{keyout.key.name}}"
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{baston_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: Bastion_host
        exact_count: 1
        count_tag:
          Name: Bastion_host
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: BastionEC2_out

    - debug:
        var: BastionEC2_out