- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vpc_setup.yml

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpcout

    - name: Create a Public subnet 1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create a Public subnet 2 in Zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create a Public subnet 3 in Zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    - name: Create  Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile_igw
      register: igw_out

    - name: Create Route table for public subnet
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
        tags:
          Name: vprofile_pubRT
      register: pubRT_out

    - debug:
        var: pubRT_out

      
    