- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vpc_setup.yml

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpcout

    - name: Create a Public subnet 1 in Zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone1}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub1
      register: pubsub1_out

    - name: Create a Public subnet 2 in Zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone2}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub2
      register: pubsub2_out

    - name: Create a Public subnet 3 in Zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone3}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: true
        region: "{{region}}"
        tags:
          Name: vprofile-pubsub3
      register: pubsub3_out

    
      
    