- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vpc_setup.yml

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
      register: vpcout

    - debug:
        var: vpcout.id

    - debug:
        msg: "{{vpcout.id}}"
    