apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vproapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: opeyemidevops.info
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: vproapp-svc
              port:
                number: 80


# Testing 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vproapp
  template:
    metadata:
      labels:
        run: vproapp
    spec:
      containers:
      - name: vproapp
        image: opeseen/tweenimg:v1
        ports:
        - name: vproapp-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-svc
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
  selector:
    run: vproapp
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vproapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: vprofile.opeyemidevops.online
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
            service:
              name: vproapp-svc
              port:
                number: 80
