kops create cluster \
  --name=kops.opeyemidevops.online \
  --state=s3://vprofile-kops01 \
  --zones=us-east-1b \
  --node-count=1 \
  --node-size=t2.micro \
  --master-size=t2.micro
  --master-volume-size=8 \
  --node-volume-size=8 \
  --dns-zone=kops.opeyemidevops.online \
  --dry-run \
  --output yaml | tee kops-opeyemidevops.yml