pipeline{
  agent any
  stages{
    stage('Fetch code from GitHub'){
      steps{
        git branch: 'master', url: 'https://github.com/Horpeyemi007/JAVA-WITH-SPRING-BOOT.git'
      }
    }
    stage('Test Job'){
			steps{
				sh 'mvn clean test'
			}
		}
		stage('Checkstyle Code Analysis'){
			steps{
				sh 'mvn checkstyle:checkstyle'
			}
			post{
				success{
					echo "Generated Analysis Result"
				}
			}
		}
    stage('Code Analysis'){
      environment {
				scannerHome = tool 'Sonar4'
			}
      steps{
        withSonarQubeEnv('sonarCloud'){
					sh '${scannerHome}/bin/sonar-scanner \
					-Dsonar.organization=horpeyemidevops \
					-Dsonar.projectKey=horpeyemidevops_jenkins-cicd -Dsonar.sources=src/ \
					-Dsonar.junit.reportsPath=target/surefire-reports/ \
					-Dsonar.junit.reportsPath=target/jacoco.exec \
					-Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
					-Dsonar.java.binaries=target/test-classes/com/opeyemi/banking/'
        }
      }
    }
  }
}