pipeline{
  agent any
  stages{
    stage('Fetch code from GitHub'){
      steps{
        git branch: 'master', url: 'https://github.com/Horpeyemi007/JAVA-WITH-SPRING-BOOT.git'
      }
    }
    stage('Test Job'){
			steps{
				sh 'mvn clean test'
			}
		}
		stage('Checkstyle Code Analysis'){
			steps{
				sh 'mvn checkstyle:checkstyle'
			}
			post{
				success{
					echo "Generated Analysis Result"
				}
			}
		}
    stage('Code Analysis'){
      def scannerHome = tool 'SonarScanner 4.0';
      steps{
        withSonarQubeEnv('sonarCloud'){
          sh '''${scannerHome}/bin/sonar-scanner -Dsonar.organization='''
        }
      }
    }
  }
}